# Generated by Django 4.2 on 2023-05-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_parentarea_competition_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='current_season_id',
            new_name='current_season',
        ),
    ]
