# Generated by Django 4.2 on 2023-05-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_rename_current_season_id_competition_current_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='current_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season'),
        ),
    ]
