# Generated by Django 4.2 on 2023-05-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_competition_current_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='crest_url',
            new_name='crest',
        ),
    ]
