# Generated by Django 4.1.3 on 2023-05-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_rename_crest_url_team_crest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('group', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='current_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='football.season'),
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('form', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('standings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.standings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
        migrations.AddField(
            model_name='standings',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings_set', to='football.competition'),
        ),
        migrations.AddField(
            model_name='standings',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season'),
        ),
        migrations.AddField(
            model_name='competition',
            name='standings',
            field=models.ManyToManyField(through='football.Standings', to='football.season'),
        ),
    ]
