# Generated by Django 4.1.3 on 2023-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_competition_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='last_updated',
            field=models.DateTimeField(default='1900-01-01', null=True),
        ),
    ]
