# Generated by Django 4.1.3 on 2023-05-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_alter_team_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='standings',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='standings',
        ),
        migrations.AddField(
            model_name='teamposition',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='football.season'),
        ),
        migrations.DeleteModel(
            name='Standings',
        ),
    ]
