# Generated by Django 4.1.3 on 2023-05-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_teamposition_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamposition',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='football.competition'),
        ),
    ]
